### ISSUE TITLE
[feature request] add option in SpamBlocker to silence calls not only block calls 

### ISSUE THREAD

**Issue by redcat42** [aj3423/SpamBlocker#32] opened 2024-05-06 10:57 UTC
thanks for your app/work

it would be great if there was a toggle switch to turn of filtering for SMS 

I would like to use it to only filter calls

I know I can not allow SpamBlocker permission to read SMS as a workaround, thought it would be cool if there was a switch button 

also, is there anything in the pipeline for silencing calls and letting them ring in the background without waking the screen or popping up the dialer when phone is unlocked and in use 

do not disturb, in android 14 allows for this kind of silencing based on do not disturb settings 

would be great to see this in SpamBlocker, I think truecaller has this feature of silencing calls, not sure though 

thanks again for your work

**Comment by aj3423** [comment] 2024-05-06 11:53
You can uncheck the SMS checkbox to disable it for SMS. I'll add a tooltip for this.
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/b1849a8f-ecf8-4b27-9d47-eb069e0230cb)

I just tried TrueCaller, seems there is a feature "Ring Silent", not sure how it works, I'll look into that later.

**Comment by redcat42** [comment] 2024-05-06 11:56
understood.

thank you. appreciate your looking into the silence calls feature.

**Comment by redcat42** [comment] 2024-05-11 07:37
> You can uncheck the SMS checkbox to disable it for SMS. I'll add a tooltip for this. ![image](https://private-user-images.githubusercontent.com/4710875/328162040-b1849a8f-ecf8-4b27-9d47-eb069e0230cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTMyNDIsIm5iZiI6MTcxNTQxMjk0MiwicGF0aCI6Ii80NzEwODc1LzMyODE2MjA0MC1iMTg0OWE4Zi1lY2Y4LTRiMjctOWQ0Ny1lYjA2OWUwMjMwY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMDczNTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUxNmVlZDJkMDM0Yjg4Yzc5Y2E5ZGYwNThmZjMwNjhlM2ZlYWJkMDc3Mjc4NTkwZjEwY2RjNjBhMWE1YjVmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NjAsxUWBq9j8MrtXxL06Xx2rrUfpKGKqLnprUF9j3vE)
> 
> I just tried TrueCaller, seems there is a feature "Ring Silent", not sure how it works, I'll look into that later.

this free, opensource app allows for the option to silence calls instead of only blocking

https://f-droid.org/packages/opencontacts.open.com.opencontacts/

https://gitlab.com/sultanahamer/OpenContacts

**Comment by aj3423** [comment] 2024-05-11 09:08
Thanks, this helps a lot, I just learnt from its source code, seems silencing a call is much easier than I thought. I'll start working on this tomorrow.

But I wonder what the use cases are. 

- TrueCaller silences calls when they should be blocked.
- OpenContacts silences or blocks non-contact numbers.

They both silence calls when they should be blocked. I don't see why this is necessary, if a call should be blocked, why not just block it? What's the point of just silencing it?

I think it's only useful when people are having video conferences, maybe they don't want to get interrupted by some less important contacts. This is what I expect this feature to be:

1. A call would be "silenced" instead of "popup and ringing" if camera or speaker is currently being used
2. And a global switch to enable/disable this feature
3. For the imortant contacts, just add them to the whitelist with higher priority

How do you think?

**Comment by redcat42** [comment] 2024-05-11 09:23
> Thanks, this helps a lot, I just learnt from its source code, seems silencing a call is much easier than I thought. I'll start working on this tomorrow.
> 
> But I wonder what the use cases are.
> 
>     * TrueCaller silences calls when they should be blocked.
> 
>     * OpenContacts silences or blocks non-contact numbers.
> 
> 
> They both silence calls when they should be blocked. I don't see why this is necessary, if a call should be blocked, why not just block it? What's the point of just silencing it?
> 
> I think it's only useful when people are having video conferences, maybe they don't want to get interrupted by some less important contacts. This is what I expect this feature to be:
> 
>     1. A call would be "silenced" instead of "popup and ringing" if camera or speaker is currently being used
> 
>     2. And a global switch to enable/disable this feature
> 
>     3. For the imortant contacts, just add them to the whitelist with higher priority
> 
> 
> How do you think?

basically, it just gives the user an option. 

For example, if you are a public figure, you have many fans, you don't want them to feel you have blocked their number, so instead you just silence the call, the person who calls just feels you are busy and have not picked up their call, this is my understanding as to why truecaller added the feature.

in short, it does not let the person calling know or feel you have blocked them. 

as far as silencing calls from people not in contacts, i have not seen any app be able to do it without waking the screen (if screen is locked) and without launching the full screen dialer (if the phone is in use) , that would be the challenge, i think truecaller does it but its source is closed

think of it as a person does not want to be disturbed by a call not in contacts, later, they can check and see if the number is important, and then call them back accordingly, in any case no one feels you have blocked them 

there is another open source app that blocks, 

https://f-droid.org/packages/org.fossify.phone/

https://github.com/FossifyOrg/Phone

but they too cannot silence the call.

Look forward to your release with silencing calls!

**Comment by aj3423** [comment] 2024-05-11 09:37
I see.
> i have not seen any app be able to do it without waking the screen (if screen is locked) and without launching the full screen dialer (if the phone is in use)

I'll try:)

**Comment by aj3423** [comment] 2024-05-11 16:51
It turns out to be easier than I expected, try this:
https://github.com/aj3423/SpamBlocker/releases/tag/latest

**Comment by redcat42** [comment] 2024-05-11 19:57
> It turns out to be easier than I expected, try this: https://github.com/aj3423/SpamBlocker/releases/tag/latest

very impressive, can't test it right now but the settings below will only allow calls from contacts and silence everything else?

![Screenshot_20240512-011929](https://github.com/aj3423/SpamBlocker/assets/113236440/0f2fe52a-d95a-43ec-a469-06100fe328a6)

**Comment by aj3423** [comment] 2024-05-11 20:07
No, the only difference is that when blocking a call, you can choose whether to silence it or reject it, just like TrueCaller.

BTW, the latest tag has a bug with the RepeatedCall and Dialed, it crashes so a call would always pass when these two are enabled,  I'm working on it...

**Comment by redcat42** [comment] 2024-05-11 20:25
> No, the only difference is that when blocking a call, you can choose whether to silence it or reject it, just like TrueCaller.
> 
> BTW, the latest tag has a bug with the RepeatedCall and Dialed, it crashes so a call would always pass when these two are enabled, I'm working on it...

ok.
I managed to test the pre-release 

https://github.com/aj3423/SpamBlocker/releases/download/latest/app-release-signed.apk

with the settings below

![329810520-0f2fe52a-d95a-43ec-a469-06100fe328a6](https://github.com/aj3423/SpamBlocker/assets/113236440/91439f7f-2f5e-4e49-81e9-ed8293f1770f)

and they worked! just wanted to let you know.

pl. feel free to close this issue 🙏
great work. thank you.

I'm sure you'll figure out the other bug!

**Comment by aj3423** [comment] 2024-05-11 21:20
Done, It's now fixed in the latest tag.

**Closed by aj3423** 2024-05-11 21:20 UTC

**Comment by redcat42** [comment] 2024-05-11 21:21
> No, the only difference is that when blocking a call, you can choose whether to silence it or reject it, just like TrueCaller.
> 
> BTW, the latest tag has a bug with the RepeatedCall and Dialed, it crashes so a call would always pass when these two are enabled, I'm working on it...

I don't know if this will help, 
when I was testing the pre-release I noticed on repeating the call once silence calls toggle was on the call log only shows the timestamp of the latest call / last call,I tried repeating calls immediately and in 2 minute intervals 

looks like the silence calls feature silences the call and stops it from being registered repeatedly in the call log 

as an option, you can let users know, if they want to use silence calls, they won't be able to use repeated calls and dialed numbers options, 

so, you can make it in such a way, if a person toggles on silence calls, the dialed numbers and repeated calls options go off or get disabled

**Comment by aj3423** [comment] 2024-05-11 21:29
> the call log only shows the timestamp of the latest call / last call

I think this might be caused by that bug, which was fixed 7 minutes ago, I guess it won't happen with the latest release.

**Comment by aj3423** [comment] 2024-05-11 21:40
Oh maybe you mean the system call log, not the local database.

**Comment by redcat42** [comment] 2024-05-11 21:43
> Oh maybe you mean the system call log, not the local database.

yup, I meant that

testing the latest, its working, however, now, if I clear the local log, and repeat calls it rings, I guess because it's reading the time from the system call log ... which is fine.

works well! :)

**Comment by aj3423** [comment] 2024-05-11 21:52
Yep, I've modified the help tooltip for RepeatedCall, it now reads system call log instead of local db, I'll mention this in the release log.

> so on a repeat call, when the phone rings, in the system call log, it looks like it was the first time that number called, actually it is the second time within 5 minutes, ;)

I also noticed this , when a call is blocked, it doesn't appear in system call log. Actually I have set `setSkipCallLog(false)`, but seems not working,  I'm now working on this.

**Comment by aj3423** [comment] 2024-05-11 22:29
Tested on  Android 10 and 14,  the problem only happens on Android 10, but on 14 it's always logged in the system call log, doesn't matter if it's silenced or rejected.

From the document: https://developer.android.com/reference/android/telecom/CallScreeningService.CallResponse.Builder#setSkipCallLog(boolean)

> Note: Calls will still be logged with type BLOCKED_TYPE

So I guess the problem is that, the default call app on Android 10 doesn't show these BLOCKED calls. Since RepeatedCall works, it queries the call log directly from its database, which means those calls are actually logged, just not listed by the call app.

Which Android version are you using?

**Comment by redcat42** [comment] 2024-05-11 22:33
> 
> Which Android version are you using?

ah, makes sense, I'm on Android 13 at the moment, will be moving to Android 14 in some time, thanks
