### ISSUE TITLE
Not work rule from more time to less time

### ISSUE THREAD

**Issue by vanek49** [aj3423/SpamBlocker#130] opened 2024-09-17 21:01 UTC
I have a contact that I want to block from 21:00 to 9:00. I give this rule a priority more than 10 to be processed before contacts. in the rule for this contact, I set the time from 21:00 to 9:00, and this time is not processed. because 21>9. 
if I set the time from 9:00 to 21:00, everything works fine.
therefore, I have to make two rules from 21:00 to 23:59 and from 00:00 to 09:00.
Is it possible to fix it or Am I doing something wrong?
![Screenshot_2024-09-17-23-59-10-569_spam blocker](https://github.com/user-attachments/assets/3fd95ff4-9933-44ec-a699-e25183ae50ef)
![Screenshot_2024-09-17-23-58-24-275_spam blocker](https://github.com/user-attachments/assets/4828948c-77d2-48a7-9569-c7a20e33f001)

**Comment by aj3423** [comment] 2024-09-18 07:26
It's by design, the format 21:00-9:00 it's only supported in OffTime, because it doesn't have a way to select days. However, for the rule schedule, when only Monday is selected, 21-9 would also affect Tuesday, that could be unexpected.

But on a second thought, people should have known this when they use such format, so I'll add support for it.

**Comment by aj3423** [comment] 2024-09-18 20:25
fixed in the action build: https://github.com/aj3423/SpamBlocker/actions/runs/10929511405

**Closed** 2024-09-26 19:24 UTC
