### ISSUE TITLE
Unable to block message from SIM2?

### ISSUE THREAD

**Issue by wdlid** [aj3423/SpamBlocker#63] opened 2024-05-31 07:31 UTC
Thanks for the great app.
In the recent days I got a few spam messages which was 'passed by default'.
But when I copy the conent and test it, it matches one of my regex and shows as block.
I found all these messages are from SIM2, is that the possible reason?

The message content is as following (sorry these are  Chinese characters):

【百度智能云】看技术大佬两天干完三周工作是怎么做到的？查看教程https://dwz.cn/5kDfzw9Q 你也能成为技术大佬。拒收请回复R

It should not be regex issue since the Test shows as blocked.

**Comment by aj3423** [comment] 2024-05-31 13:11
It should work fine for dual SIM, I tested it with v1.8, it worked.
However, I just found another issue when testing this, the SMS Receiver is supposed to work even when the app is killed, but it doesn't work on some phone, not working on my Samsung S21 but works fine on Asus Zenfone and emulators. I don't know if it's related, but if this is the case, there should be no record appear in the SMS log, no "passed by default". 
Can you try to kill the app process and test it again? If this is not the reason, can you show me a minimal reproducible config?

**Comment by wdlid** [comment] 2024-06-06 01:36
Thanks for the reply.
This is a Samsung S23.
'passed by default'  is not caused by killed.

This issue happens only for my SIM2.
Here is my full configuration, as you can see, the messages in my example should match the first rule pattern (拒收请).

``` json
{
  "global": {
    "enabled": true
  },
  "theme": {},
  "contacts": {},
  "repeatedCall": {
    "times": 1,
    "inXMin": 5
  },
  "dialed": {
    "inXDay": 3
  },
  "recentApps": {
    "inXMin": 5
  },
  "silence": {},
  "offTime": {},
  "numberRules": {},
  "contentRules": {
    "rules": [{
      "id": 11,
      "pattern": ".*(交通委|联合会|林业局|信息化部|拒收请|拒收回).*",
      "patternFlags": {
        "value": 0
      },
      "patternExtraFlags": {
        "value": 0
      },
      "flagCallSms": {
        "value": 3
      }
    }, {
      "id": 6,
      "pattern": ".*(公益短信).*",
      "patternFlags": {
        "value": 0
      },
      "patternExtraFlags": {
        "value": 0
      },
      "flagCallSms": {
        "value": 3
      }
    }, {
      "id": 3,
      "pattern": ".*(反诈|诈骗).*",
      "patternFlags": {
        "value": 0
      },
      "patternExtraFlags": {
        "value": 0
      },
      "flagCallSms": {
        "value": 3
      }
    }, {
      "id": 9,
      "pattern": ".*(妇联|电信日|气象局).*",
      "patternFlags": {
        "value": 0
      },
      "patternExtraFlags": {
        "value": 0
      },
      "flagCallSms": {
        "value": 3
      }
    }, {
      "id": 7,
      "pattern": ".*(宣传部|海警局|海事局|中宣部).*",
      "patternFlags": {
        "value": 0
      },
      "patternExtraFlags": {
        "value": 0
      },
      "flagCallSms": {
        "value": 3
      }
    }, {
      "id": 8,
      "pattern": ".*(总公会|监管局|网信办).*",
      "patternFlags": {
        "value": 0
      },
      "patternExtraFlags": {
        "value": 0
      },
      "flagCallSms": {
        "value": 3
      }
    }, {
      "id": 2,
      "pattern": ".*(森防办|预警|查看惊喜).*",
      "patternFlags": {
        "value": 0
      },
      "patternExtraFlags": {
        "value": 0
      },
      "flagCallSms": {
        "value": 3
      }
    }, {
      "id": 12,
      "pattern": ".*(粮食日|先进分|祭扫|举报|安全教育日).*",
      "patternFlags": {
        "value": 0
      },
      "patternExtraFlags": {
        "value": 0
      },
      "flagCallSms": {
        "value": 3
      }
    }, {
      "id": 1,
      "pattern": ".*(退订|TD退|澳门).*",
      "patternFlags": {
        "value": 0
      },
      "patternExtraFlags": {
        "value": 0
      },
      "flagCallSms": {
        "value": 3
      }
    }, {
      "id": 10,
      "pattern": ".*(通信管理局|中宣部|公安厅).*",
      "patternFlags": {
        "value": 0
      },
      "patternExtraFlags": {
        "value": 0
      },
      "flagCallSms": {
        "value": 3
      }
    }]
  },
  "quickCopyRules": {
    "rules": [{
      "id": 2,
      "pattern": "code.*?(\\d+)",
      "patternFlags": {
        "value": 5
      },
      "patternExtraFlags": {
        "value": 5
      },
      "description": "Code",
      "priority": 2,
      "isBlacklist": false,
      "flagCallSms": {
        "value": 3
      }
    }, {
      "id": 1,
      "pattern": "验证码.*?(\\d+)",
      "patternFlags": {
        "value": 5
      },
      "patternExtraFlags": {
        "value": 5
      },
      "description": "验证码",
      "isBlacklist": false,
      "flagCallSms": {
        "value": 3
      }
    }]
  }
}
```

Any more debug logs I can provided?

**Comment by aj3423** [comment] 2024-06-06 04:24
It turns out that a single long message is split into multiple parts due to character limitations of SMS messages, this message is split into:

【百度智能云】...... 拒收
and
请回复R

That's why it doesn't match, it has been fixed in the action build: https://github.com/aj3423/SpamBlocker/actions/runs/9395012270

**Comment by wdlid** [comment] 2024-06-06 05:32
it crashs always with error: 

```
java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:476)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:54)
	at spam.blocker.db.RuleTable.listByFilter(RuleTable.kt:131)
	at spam.blocker.db.RuleTable.listRules(RuleTable.kt:202)
	at spam.blocker.db.RuleTable.listAll(RuleTable.kt:173)
	at spam.blocker.ui.setting.SettingFragment$setupRules$asyncReloadFromDb$1.invokeSuspend(SettingFragment.kt:618)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@53951b5, Dispatchers.IO]

```

**Comment by aj3423** [comment] 2024-06-06 06:03
fixed in this build: https://github.com/aj3423/SpamBlocker/actions/runs/9395860152

**Closed** 2024-06-09 01:14 UTC
