### ISSUE TITLE
[Feature Request] hide app in recent app

### ISSUE THREAD

**Issue by wdlid** [aj3423/SpamBlocker#107] opened 2024-08-08 12:04 UTC
Thanks for the great app again~
I used this app daily almost from day one~

May need a feature to hide this app in recent app list.
A new switch could be added to toggle this feature.

Because sometimes when I on default sms app and use full screen gesture by swipe right in the bottom, since this app is most recent one, it will automatically switch to default sms app again.

Thanks

**Comment by aj3423** [comment] 2024-08-08 14:28
I also have this problem occasionally, it is related to switching to SMS app by clicking the history record or notification.
But now I can't reproduce it, can you show me the steps to reproduce it?

**Comment by wdlid** [comment] 2024-08-08 14:59
Yes, I also saw this issue when I was on a third app. 
When click login with sms, then new sms comes in. I click the notification 
after that it will open default sms app.
then if you want switch back to third app with gesture, it will always switch back to default sms app since our app is on the most recent.

I see  some othet apps have feature to hide themself in the recent app list.

**Comment by aj3423** [comment] 2024-08-08 16:52
Fixed in the action build: https://github.com/aj3423/SpamBlocker/actions/runs/10306155341

There won't be ghost process when launched from clicking the notification anymore, and it doesn't affect the normal usage, no need for a new option.

**Comment by Ra2-IFV** [comment] 2024-08-12 02:40
> Fixed in the action build: https://github.com/aj3423/SpamBlocker/actions/runs/10306155341
> 
> There won't be ghost process anymore when launched from clicking the notification, and it doesn't affect the normal usage, no need for a new option.

Perfect! I had this problem a few months but I wonder if most people use it

**Closed** 2024-08-12 08:06 UTC
